version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule: 
      interval: "weekly"
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "@angular*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
