version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule: 
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
