name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  frontend:
    uses: ./.github/workflows/frontend.yml
  backend:
    uses: ./.github/workflows/backend.yml

  dockerize_dev:
    name: Dockerize Development Version
    needs:
      - frontend
      - backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: ./frontend/dist
      - name: Download backend
        uses: actions/download-artifact@v4
        with:
          name: backend
      - name: Fix permissions
        run: chmod +x full-house
      - name: Build image
        run: docker build -t philmtd/full-house:latest-dev .
      - name: Push image
        run: docker push philmtd/full-house:latest-dev