name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dockerize_dev:
    name: Dockerize Development Version
    needs:
      - frontend
      - backend
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "test"