name: Dockerize

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      latest:
        type: boolean
        default: false
        required: false
      push:
        type: boolean
        default: true
        required: false

jobs:
  dockerize:
    name: Dockerize Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download frontend
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: ./frontend/dist
      - name: Download backend
        uses: actions/download-artifact@v4
        with:
          name: backend
      - name: Fix permissions
        run: chmod +x full-house
      - name: Build image
        run: docker build -t philmtd/full-house:${{ inputs.tag }} .
      - name: Push image
        if: ${{ inputs.push }}
        run: docker push philmtd/full-house:${{ inputs.tag }}
      - name: Tag latest
        if: ${{ inputs.latest }}
        run: docker tag philmtd/full-house:${{ inputs.tag }} philmtd/full-house:latest
      - name: Push latest
        if: ${{ inputs.latest && inputs.push }}
        run: docker push philmtd/full-house:latest